site_name: Simple Popup Block
theme:
  name: material

extra_css:
  - css/extra.css

plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Choose a Template: template.md
  - Popup Trigger: popup-trigger.md
  - Popup Behavior: popup-behavior.md
  - Popup Condition: popup-condition.md
  - Dimension: dimension.md
  - Close Button: close-button.md
  - Tutorial:
      - 'Display On Whole Site': 'display-on-whole-site.md'
      - 'Show popup on click': 'trigger-on-click.md'
      - 'Show Video in popup': 'embed-video-in-popup.md'
