site_name: Simple Popup Block
theme:
  name: material

nav:
  - Introduction: index.md
  - Installation: installation.md
  - About: about.md
  - Dimension: dimension.md
  - Close Button: close-button.md
 