site_name: Simple Popup Block
theme:
  name: material

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Popup Trigger: popup-trigger.md
  - Popup Behavior: popup-behavior.md
  - Popup Condition: popup-condition.md
  - About: about.md
  - Dimension: dimension.md
  - Close Button: close-button.md
 